version: '3.1'
services:
  web:
    image: frojd/company_project_web
    build: ./src
    volumes:
      - "./src:/app:cached"
      - "./docker/files/shared:/shared:rw"
      - "./docker/files/var/log:/var/log:rw"
      - "./docker/files/certs:/priv/cert:cached"
    ports:
      - "8081:8000"
      - "5678:5678"
    depends_on:
      - db
    env_file: ./docker/config/web.env
  frontend:
    image: frojd/company_project_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app:cached"
      - "./src:/webapp:cached"
    ports:
      - "3000:3000"
  storybook:
    image: frojd/company_project_frontend
    volumes:
      - "./frontend:/app:cached"
    ports:
      - "3001:3001"
    depends_on:
      - frontend
    environment:
      - CRA_PUBLIC_URL=/proxy
    command: storybook
  ssr:
    image: frojd/company_project_frontend
    volumes:
      - "./frontend:/app:cached"
    ports:
      - "3030:3030"
    depends_on:
      - frontend
    environment:
      - HYPERNOVA_DISABLE_MODULE_CACHE=1
      - CRA_PUBLIC_URL=/proxy
      - HYPERNOVA_DEV_MODE=1
    command: hypernova
  db:
    image: mdillon/postgis:10
    ports:
      - "8082:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/:cached"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
